# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 540)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tabNetwork = QtWidgets.QWidget()
        self.tabNetwork.setObjectName("tabNetwork")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.tabNetwork)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.viewNetwork = QtWidgets.QTreeView(self.tabNetwork)
        self.viewNetwork.setObjectName("viewNetwork")
        self.horizontalLayout_3.addWidget(self.viewNetwork)
        self.tabWidget.addTab(self.tabNetwork, "")
        self.tabData = QtWidgets.QWidget()
        self.tabData.setObjectName("tabData")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tabData)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tableData = QtWidgets.QTableView(self.tabData)
        self.tableData.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableData.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableData.setObjectName("tableData")
        self.horizontalLayout_2.addWidget(self.tableData)
        self.tabWidget.addTab(self.tabData, "")
        self.tabTraffic = QtWidgets.QWidget()
        self.tabTraffic.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabTraffic.setObjectName("tabTraffic")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tabTraffic)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.textTraffic = QtWidgets.QPlainTextEdit(self.tabTraffic)
        self.textTraffic.setObjectName("textTraffic")
        self.verticalLayout_2.addWidget(self.textTraffic)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.checkRaw = QtWidgets.QCheckBox(self.tabTraffic)
        self.checkRaw.setChecked(True)
        self.checkRaw.setObjectName("checkRaw")
        self.horizontalLayout.addWidget(self.checkRaw)
        self.buttonStart = QtWidgets.QPushButton(self.tabTraffic)
        self.buttonStart.setObjectName("buttonStart")
        self.horizontalLayout.addWidget(self.buttonStart)
        self.buttonStop = QtWidgets.QPushButton(self.tabTraffic)
        self.buttonStop.setEnabled(False)
        self.buttonStop.setObjectName("buttonStop")
        self.horizontalLayout.addWidget(self.buttonStop)
        self.buttonClear = QtWidgets.QPushButton(self.tabTraffic)
        self.buttonClear.setObjectName("buttonClear")
        self.horizontalLayout.addWidget(self.buttonClear)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.tabWidget.addTab(self.tabTraffic, "")
        self.tabPFD = QtWidgets.QWidget()
        self.tabPFD.setObjectName("tabPFD")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.tabPFD)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.gviewPFD = QtWidgets.QGraphicsView(self.tabPFD)
        self.gviewPFD.setObjectName("gviewPFD")
        self.horizontalLayout_5.addWidget(self.gviewPFD)
        self.tabWidget.addTab(self.tabPFD, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 30))
        self.menubar.setObjectName("menubar")
        self.menuComm = QtWidgets.QMenu(self.menubar)
        self.menuComm.setObjectName("menuComm")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menu_Tools = QtWidgets.QMenu(self.menubar)
        self.menu_Tools.setObjectName("menu_Tools")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionConnect = QtWidgets.QAction(MainWindow)
        self.actionConnect.setObjectName("actionConnect")
        self.actionDisconnect = QtWidgets.QAction(MainWindow)
        self.actionDisconnect.setEnabled(False)
        self.actionDisconnect.setObjectName("actionDisconnect")
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_As = QtWidgets.QAction(MainWindow)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionLoad_Firmware = QtWidgets.QAction(MainWindow)
        self.actionLoad_Firmware.setObjectName("actionLoad_Firmware")
        self.actionSave_Node_Configuration = QtWidgets.QAction(MainWindow)
        self.actionSave_Node_Configuration.setObjectName("actionSave_Node_Configuration")
        self.actionLoad_Node_Configuration = QtWidgets.QAction(MainWindow)
        self.actionLoad_Node_Configuration.setObjectName("actionLoad_Node_Configuration")
        self.menuComm.addAction(self.actionConnect)
        self.menuComm.addAction(self.actionDisconnect)
        self.menuFile.addAction(self.actionExit)
        self.menu_Tools.addAction(self.actionSave_Node_Configuration)
        self.menu_Tools.addAction(self.actionLoad_Node_Configuration)
        self.menu_Tools.addSeparator()
        self.menu_Tools.addAction(self.actionLoad_Firmware)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuComm.menuAction())
        self.menubar.addAction(self.menu_Tools.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.actionConnect.triggered.connect(MainWindow.connect)
        self.actionExit.triggered.connect(MainWindow.close)
        self.tableData.doubleClicked['QModelIndex'].connect(MainWindow.dataEdit)
        self.actionLoad_Firmware.triggered.connect(MainWindow.loadFirmware)
        self.actionDisconnect.triggered.connect(MainWindow.disconnect)
        self.viewNetwork.clicked['QModelIndex'].connect(MainWindow.networkClicked)
        self.buttonClear.clicked.connect(self.textTraffic.clear)
        self.buttonStart.clicked.connect(MainWindow.trafficStart)
        self.buttonStop.clicked.connect(MainWindow.trafficStop)
        self.viewNetwork.expanded['QModelIndex'].connect(MainWindow.networkExpanded)
        self.viewNetwork.doubleClicked['QModelIndex'].connect(MainWindow.networkDblClicked)
        self.viewNetwork.customContextMenuRequested['QPoint'].connect(MainWindow.networkContextMenu)
        self.viewNetwork.collapsed['QModelIndex'].connect(MainWindow.networkCollapsed)
        self.actionSave_Node_Configuration.triggered.connect(MainWindow.saveConfiguration)
        self.actionLoad_Node_Configuration.triggered.connect(MainWindow.loadConfiguration)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CAN-FIX Configuration Utility"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabNetwork), _translate("MainWindow", "Network"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabData), _translate("MainWindow", "Data"))
        self.checkRaw.setText(_translate("MainWindow", "Raw"))
        self.buttonStart.setText(_translate("MainWindow", "Start"))
        self.buttonStop.setText(_translate("MainWindow", "Stop"))
        self.buttonClear.setText(_translate("MainWindow", "Clear"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabTraffic), _translate("MainWindow", "Traffic"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabPFD), _translate("MainWindow", "PFD"))
        self.menuComm.setTitle(_translate("MainWindow", "&Comm"))
        self.menuFile.setTitle(_translate("MainWindow", "&File"))
        self.menu_Tools.setTitle(_translate("MainWindow", "&Tools"))
        self.actionConnect.setText(_translate("MainWindow", "&Connect..."))
        self.actionConnect.setShortcut(_translate("MainWindow", "Meta+C"))
        self.actionDisconnect.setText(_translate("MainWindow", "&Disconnect"))
        self.actionDisconnect.setShortcut(_translate("MainWindow", "Meta+D"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionOpen.setText(_translate("MainWindow", "Open..."))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave_As.setText(_translate("MainWindow", "Save As..."))
        self.actionExit.setText(_translate("MainWindow", "&Exit"))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionLoad_Firmware.setText(_translate("MainWindow", "Load &Firmware"))
        self.actionLoad_Firmware.setShortcut(_translate("MainWindow", "Ctrl+Alt+F"))
        self.actionSave_Node_Configuration.setText(_translate("MainWindow", "Save Node Configuration"))
        self.actionLoad_Node_Configuration.setText(_translate("MainWindow", "Load Node Configuration"))

